version: "3"
services:
  compass:
    image: "iotacafe/compass:coordinator-554440c"
    networks:
      - web
    depends_on:
      - "iri"
    volumes:
      - .\state:/state
      - .\layers:/layers
    command: coordinator_deploy.jar
      -broadcast
      -bootstrap
      -layers /layers
      -sigMode CURLP27
      -powMode CURLP81
      -mwm 5
      -security 1
      -seed MYSEEDHEREPLEASEREPLACEMEIMMEDIATELYWITHSOMETHINGSECURE99999999999999999999999999
      -tick 30000
      -host http://iri:14265
      -statePath /state/statefile
  iri:
    image: "iotaledger/iri:latest"
    ports:
      - 14265:14265
      - 5556:5556
    networks:
      - web
    volumes:
      - ./snapshot.txt:/snapshot.txt
      - iri-db:/iri/data
    command: >-
      --testnet 
      --remote 
      --testnet-coordinator ZRMNUUBQHVRFRFBOQZYGAUBSTJSHDVIPXHUDA9VAXFTDSGGRILPVMYLVOLVCIEHLFMQKUOHUIUWILCXGD
      --testnet-coordinator-security-level 1
      --testnet-coordinator-signature-mode CURLP27
      --mwm 5
      --milestone-start 0
      --milestone-keys 20
      --snapshot /snapshot.txt
      --max-depth 1000
      --zmq-enabled true
      --remote-limit-api removeNeighbors,addNeighbors,getNeighbors,setApiRateLimit
volumes:
  iri-db:
networks:
  web:
    external: true
