# build definition
parameters:
  appName: ''
  pool: ''
  npmFeed: 'FZI-IOTA-NPM'

jobs:
- job: Build 
  pool: ${{ parameters.pool }}
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  
  - script: |
      cp ../azure-pipelines/scripts/process-coverage-report.js ./
      rm package-lock.json
    workingDirectory: $(app_path)
    displayName: Copy code coverage scrip
  
  - task: Npm@1
    displayName: NPM install
    inputs:
      command: 'install' 
      workingDir: $(app_path) 
      customRegistry: useFeed
      customFeed: ${{ parameters.npmFeed }}   


  - task: Npm@1
    continueOnError: true
    displayName: NPM build
    inputs:
      command: 'custom' 
      customCommand: run-script build
      workingDir: $(app_path) 
        
  - task: Npm@1
    continueOnError: true
    displayName: NPM test
    inputs:
      command: 'custom' 
      customCommand: run-script coverage
      workingDir: $(app_path)   
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
      testResultsFiles: '**/test-results.xml' 
      #searchFolder: $(app_path) # Optional
      #mergeTestResults: false # Optional
      #failTaskOnFailedTests: false # Optional
      testRunTitle: $(app_path) Unit Tests # Optional
      #buildPlatform: # Optional
      #buildConfiguration: # Optional
      #publishRunAttachments: true # Optional

      # Publish Code Coverage Results
# Publish Cobertura or JaCoCo code coverage results from a build
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura' # Options: cobertura, jaCoCo
      summaryFileLocation: $(app_path)/coverage/cobertura-coverage.xml
      reportDirectory: $(app_path)/coverage # Optional
      #additionalCodeCoverageFiles: # Optional
      #failIfCoverageEmpty: false # Optional
  - task: Npm@1
    continueOnError: true
    displayName: NPM package
    inputs:
      command: 'custom' 
      customCommand: pack
      workingDir: $(app_path) 
  

  
  - script: |
      mkdir publish
      mv *.tgz ./publish/
    workingDirectory: $(app_path)

  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifact
    inputs:
      ArtifactName: package
      PathtoPublish: $(app_path)/publish