# build definition
parameters:
  appName: ''
  pool: ''

jobs:
- job: Build 
  pool: ${{ parameters.pool }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  
  - template: ../steps/docker.yml
