# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


variables:
- group: dockerRegistry
- name: app_path
  value: backend
- name: app_name
  value: Backend


trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'backend/*'


jobs:
- template: jobs/build-node.yml  # Template reference
  parameters:
    app_name: $(app_name)
    test: true
    pool:
      vmImage: 'ubuntu-16.04'
 