# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
- group: dockerRegistry
- name: app_path
  value: showcase-user-interface
- name: app_name
  value: Showcase user-interface


trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'showcase-user-interface/*'
    - 'showcase-user-interface-build.yml'


jobs:
- template: jobs/build-vue.yml  # Template reference
  parameters:
    app_name: $(app_name)
    pool:
      vmImage: 'ubuntu-16.04'
 